# Config file generated by terravarmer
# When creating multiple bits of infrastructure from one terraform module we have to dynamically inject
# the terraform config file to ensure the remote state is stored and can be retrieved correctly
terraform {
  required_providers {
    aws = {
      version = ">= 3.0"
      source  = "hashicorp/aws"
    }
  }
  backend "s3" {
    key     = "BACKEND_S3_KEY"
  }
}

provider "aws" {
  profile                 = var.profile
  region                  = var.region
}
